parameters:
- name: resource
  type: object

jobs:
  - job: BuildJob
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x'
        displayName: 'Install Node.js'

      - task: Npm@1
        inputs:
          command: 'install'
          verbose: true
          workingDir: '$(Build.Repository.LocalPath)/examples/datafactory/src'
        displayName: 'Install npm package'

      - powershell: |
          cd $(Build.Repository.LocalPath)/examples/datafactory/src
          Get-ChildItem -Recurse

      - task: Npm@1
        inputs:
          command: 'custom'
          customCommand: 'run build export $(Build.Repository.LocalPath)/examples/datafactory/src /subscriptions/337ba254-3aa0-4551-ba8e-89debefaa373/resourceGroups/RG-Datafactory/providers/Microsoft.DataFactory/factories/adf-testdeploywes artifacts'
          workingDir: '$(Build.Repository.LocalPath)/examples/datafactory/src'
        displayName: 'Validate and Generate ARM template'

      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(build.artifactstagingdirectory)'
          Contents: '**/artifacts/**'
          TargetFolder: '$(Pipeline.Workspace)/datafactory'



      - task: PublishPipelineArtifact@1
        inputs:
          targetPath: '$(build.artifactstagingdirectory)/datafactory'
          artifact: 'ArmTemplates'
          publishLocation: 'pipeline'