resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: wesleycamargo
    name: wesleycamargo/UDP

trigger:
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

steps:
  - powershell: Get-ChildItem $(Build.SourcesDirectory)/examples -Recurse

# extends:
#   template: src\orchestrator.yml@UDP
#   parameters:
#     resourceType: dotnetcore

