# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    serviceConnection: 'MVP Sponsorship'
    environments:
      - dev
      - uat
    configuration:
      resources:
        - type: dotnetcore
          enabled: true
          deployment:
            azureWebApp:
              name: webAppUDP
            infrastructure:
              enabled: false
            application:
              enabled: false