# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

# extends:
#   # If you are using this example in your oun repository, 
#   # you need to uncomment the next line and comment the line streight below
#   #template: src\orchestrator.yml@UDP 
#   template: ..\..\src\orchestrator.yml
#   parameters:
#     resourceType: dotnetcore

jobs:
  - template: ..\..\src\orchestrator.yml
    parameters:
      resourceType: dotnetcore
  
  - deployment: 
    environment: develop
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'ServiceConnection'
                appType: 'webApp'
                WebAppName: 'wa-udp-dotnetcore'
                packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'

    
