resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: wesleycamargo
    name: wesleycamargo/UDP

trigger:
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

steps:
  - powershell: Get-ChildItem $(Build.SourcesDirectory)/examples -Recurse

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '$(Build.SourcesDirectory)/**/*.csproj'

# extends:
#   template: src\orchestrator.yml@UDP
#   parameters:
#     resourceType: dotnetcore

