resources:
  repositories:
  - repository: UDP
    type: github
    endpoint: wesleycamargo
    name: wesleycamargo/UDP
    ref: refs/heads/feature/includeexamples

trigger:
  - feature/*
  
pool:
  vmImage: 'ubuntu-latest'

extends:
  template: src\orchestrator.yml@UDP
  parameters:
    resourceType: dotnetcore

