# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*
  
pool:
  vmImage: 'windows-latest'

variables:
  - group: vg-global
  # - name: serviceConnection
  #   value: 'MVP Sponsorship'
  # - name: ServiceConnectionName
  #   value: 'MVP Sponsorship'
  # # - name: spnClientId
  # # - name: spnClientSecret
  # - name: subscriptionId
  #   value: '337ba254-3aa0-4551-ba8e-89debefaa373'

  # - name: tenant

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    resourceType: databricks
    environments:
      - dev
      # - uat
    configuration:
      keyVaultName: udp-keyvault
      appConfigName: udp-appconfig
      resourceGroup: RG-DataOps
      resources:
        - name: dataplatform-batchprocessing-infrastructure
          type: dataplatform-batchprocessing-infrastructure
          enabled: true
          dataFactory:
            name: udp-dataFactory
          storageAccount:
            name: udpstorage2
          blobContainer:
            name: udpcontainer
          databricksWorkspace:
            keyVaultPATSecretName: dbtoken
            name: udp-databricksWorkspace
            clusters:
              - name: udp-cluster
                clusterConfigurationFile: $(System.ArtifactsDirectory)\application\databricks\configuration\clusterconfig.json
      
        - name: databricks-udp2
          type: databricks
          databricksWorkspaceResourceGroup: "RG-ARMdatapipeline"
          keyVaultPATSecretName: dbtoken
          enabled: false
          infrastructure:
            enabled: false
            runTests: false
            clusters:
              - name: new-cluster
                clusterConfigurationFile: $(System.ArtifactsDirectory)\application\databricks\configuration\clusterconfig.json
          application:
            enabled: true
            workspaceDirectory: /deployments/