# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*
  
pool:
  vmImage: 'windows-latest'

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    resourceType: databricks
    resources:
      - name: databricks
        type: databricks
        infrastructure:
          clusters:
            - name: new-cluster