# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

trigger:
  - main
  - feature/*
  
pool:
  vmImage: 'windows-latest'

variables:
  - name: serviceConnection
    value: 'MVP Sponsorship'
  - name: ServiceConnectionName
    value: 
  - name: spnClientId
  - name: spnClientSecret
  - name: subscriptionId
  - name: tenant

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    resourceType: databricks
    resources:
      - name: databricks
        type: databricks
        databricksWorkspaceResourceGroup: "RG-ARMdatapipeline"
        infrastructure:
          clusters:
            - name: new-cluster
              clusterConfigurationFile: $(System.ArtifactsDirectory)\databricks\application\clusterconfig.json
            - name: new-cluster-5
              clusterConfigurationFile: $(System.ArtifactsDirectory)\databricks\application\clusterconfig.json