# If you are using this example in your oun repository, 
# you need to uncomment the lines below:
# resources:
#   repositories:
#   - repository: UDP
#     type: github
#     endpoint: devopsnights
#     name: devopsnights/UDP
#     ref: refs/heads/main

# trigger:
#   - main
#   - feature/*

trigger:
  branches:
    include:
    - feature/*
  paths:
    include:
    - examples/datafactory


trigger:
  branches:
    include:
    - feature/*
  paths:
    include:
    - examples/datafactory

pool:
  vmImage: 'windows-latest'

extends:
  # If you are using this example in your oun repository, 
  # you need to uncomment the next line and comment the line streight below
  #template: src\orchestrator.yml@UDP 
  template: ..\..\src\orchestrator.yml
  parameters:
    serviceConnection: 'AzureServiceConnection'
    environments:
      - dev
      # - uat
      # - prd
    configuration:
      buildOnly: true
      resources:
        - type: datafactory
          enabled: true
          