parameters:
- name: resourceType 
  type: string 
- name: webAppName 
  default: ''
  type: string
- name: serviceConnection
  default: ''  
  type: string
- name: resources
  type: object
- name: environments 
  type: object

stages:
- stage: build
  dependsOn: []
  jobs:

    - ${{ each resource in parameters.resources }}:
      - ${{ if eq(resource.type, 'databricks') }}:
          - template: .\build\databricks-build-jobs.yml 
            parameters: 
              resourceConfiguration: ${{ resource }}
          - template: .\deploy\databricks-deploy-jobs.yml 
            parameters:
              resourceConfiguration: ${{ resource }}

- ${{ each env in parameters.environments }}:
  # - ${{ each opCo in parameters.opCos }}:
  - stage:  ${{ env }}
    ${{ if eq(env, 'dev') }}:
      condition: >-
        and( succeeded(),
          or( eq(variables['Build.SourceBranch'], 'refs/heads/develop'),
              startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'),
              startsWith(variables['Build.SourceBranch'], 'refs/heads/users/')
            )
          )
      dependsOn: 
        - build

  # - ${{ if eq(parameters.resourceType, 'dotnetcore') }}:    
  #     - template: .\build\dotnetcore-build-jobs.yml
  
  # - ${{ if eq(parameters.resourceType, 'nodejs') }}:
  #     - template: .\build\nodejs-build-jobs.yml 

  # - template: .\deploy\azure-webapp-deploy-jobs.yml
  #   parameters:
  #     webAppName: ${{ parameters.webAppName }}
  #     serviceConnection: ${{ parameters.serviceConnection }}