jobs:
  - deployment: 
    displayName: Azure Web App Deployment
    environment: develop
    dependsOn: BuildJob
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: 'ServiceConnection'
                appType: 'webApp'
                WebAppName: 'wa-udp-dotnetcore'
                packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'