parameters:
  - name: resourceConfiguration
    type: object

jobs:
  - deployment: 
    displayName: Azure Databricks Deployment
    environment: develop
    dependsOn: databricksbuild
    strategy:
      runOnce:
        deploy:
          steps:
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'databricks'
                downloadPath: '$(System.ArtifactsDirectory)'

            - powershell: |
                cd $(System.ArtifactsDirectory)
                Get-ChildItem -Recurse

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'MVP Sponsorship'
                subscriptionId: '337ba254-3aa0-4551-ba8e-89debefaa373'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'RG-ARMdatapipeline'
                location: 'North Europe'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.ArtifactsDirectory)\databricks\infrastructure\databricks.json'
                deploymentMode: 'Incremental'
            
            - ${{ each cluster in parameters.resourceConfiguration.infrastructure.clusters }}:
                - task: AzureCLI@2
                  displayName: Create Cluster
                  inputs:
                    azureSubscription: $(ServiceConnectionName)
                    scriptLocation: "scriptPath"
                    scriptType: "pscore"
                    scriptPath: '$(System.ArtifactsDirectory)\databricks\infrastructure\New-DatabricksCluster.ps1'
                    arguments: >
                      -clusterName ${{ cluster.name }}
                      -clusterConfigurationFile $(System.ArtifactsDirectory)\databricks\infrastructure\clusterconfig.json
                      -databricksWorkspaceURL "https://adb-7228147700679055.15.azuredatabricks.net"
                      -databricksResourceId "/subscriptions/337ba254-3aa0-4551-ba8e-89debefaa373/resourceGroups/RG-ARMdatapipeline/providers/Microsoft.Databricks/workspaces/databricks5zpayvr2rt6ki"
                      -tenant $(tenant)
                      -spnClientId $(spnClientId)
                      -spnClientSecret $(spnClientSecret)
