parameters:
  - name: configuration
    type: object
  - name: resource
    type: object

jobs:
  - deployment: 
    displayName: Azure Databricks Deployment
    environment: develop
    strategy:
      runOnce:
        preDeploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'application'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'infrastructure'
                downloadPath: '$(System.ArtifactsDirectory)'

            - powershell: |
                Get-ChildItem $(System.ArtifactsDirectory) -Recurse

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: $(serviceConnection)
                subscriptionId: $(subscriptionId)
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.resource.databricksWorkspaceResourceGroup }}
                location: 'North Europe'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.ArtifactsDirectory)\infrastructure\databricks\databricks.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'
                overrideParameters: |
                  -databricksWorkspaceName ${{ parameters.resource.name }}
            
            - powershell: |
                Write-Host "output $($armOutputObj.workspace)"

            - powershell: |
                function Convert-ArmOutputToPsObject {
                  param (
                    [Parameter(Mandatory=$true)]
                    [string]
                    $ArmOutputString
                  )

                  if ($PSBoundParameters['Verbose']) {
                    Write-Host "Arm output json is:"
                    Write-Host $ArmOutputString
                  }

                  $armOutputObj = $ArmOutputString | ConvertFrom-Json

                  $armOutputObj.PSObject.Properties | ForEach-Object {
                      $type = ($_.value.type).ToLower()
                      $keyname = "ArmOutputs.$($_.name)"
                      $value = $_.value.value

                      if ($type -eq "securestring") {
                          Write-Host "##vso[task.setvariable variable=$keyname;issecret=true]$value"
                          Write-Host "Added Azure DevOps secret variable '$keyname' ('$type')"
                      } elseif ($type -eq "string") {
                          Write-Host "##vso[task.setvariable variable=$keyname]$value"
                          Write-Host "Added Azure DevOps variable '$keyname' ('$type') with value '$value'"
                      } else {
                          Throw "Type '$type' is not supported for '$keyname'"
                      }
                  }
                }

                Convert-ArmOutputToPsObject -ArmOutputString '$(ArmOutputs)' -Verbose
              displayName: "Parsing outputs from ARM deployment to pipeline variables"
              
            - powershell: |
                Write-Host "output $(ArmOutputs.databricksWorkspaceName)"
                Write-Host "output $(ArmOutputs.workspaceUrl)"
                
                

            
            - task: AzureCLI@2
              displayName: Register Databricks PAT
              inputs:
                azureSubscription: $(ServiceConnectionName)
                scriptLocation: "scriptPath"
                scriptType: "pscore"
                scriptPath: '$(System.ArtifactsDirectory)\infrastructure\databricks\Register-DatabricksPAT.ps1'
                arguments: >
                  -spnClientId $(spnClientId)
                  -spnClientSecret $(spnClientSecret)
                  -databricksWorkspaceName $(ArmOutputs.databricksWorkspaceName)
                  -databricksWorkspaceResourceGroup ${{ parameters.resource.databricksWorkspaceResourceGroup }}
                  -keyVaultName ${{ parameters.configuration.keyVaultName }} 
                  -keyVaultPATSecretName ${{ parameters.resource.keyVaultPATSecretName }}

            - ${{ each cluster in parameters.resource.infrastructure.clusters }}:
                - task: AzureCLI@2
                  displayName: Create Cluster
                  inputs:
                    azureSubscription: $(ServiceConnectionName)
                    scriptLocation: "scriptPath"
                    scriptType: "pscore"
                    scriptPath: '$(System.ArtifactsDirectory)\infrastructure\databricks\New-DatabricksCluster.ps1'
                    arguments: >
                      -clusterName ${{ cluster.name }}
                      -clusterConfigurationFile ${{ cluster.clusterConfigurationFile }}
                      -tenant $(tenant)
                      -spnClientId $(spnClientId)
                      -spnClientSecret $(spnClientSecret)
                      -databricksWorkspaceName $(ArmOutputs.databricksWorkspaceName)
                      -databricksWorkspaceResourceGroup ${{ parameters.resource.databricksWorkspaceResourceGroup }}

            - task: Pester@9
              inputs:
                # Required Arguments
                scriptFolder: "@{Path='$(System.ArtifactsDirectory)/tests'; Parameters=@{spnClientSecret='$(spnClientSecret)';spnClientId='$(spnClientId)';databricksWorkspaceName='${{ parameters.resource.name }}';databricksWorkspaceResourceGroup='${{ parameters.resource.databricksWorkspaceResourceGroup }}';keyVaultName='${{ parameters.configuration.keyVaultName }}';keyVaultPATSecretName='${{ parameters.resource.keyVaultPATSecretName }}'}"
                resultsFile: '$(System.ArtifactsDirectory)\Test-Pester.XML'
                
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              displayName: Downloading artifacts databricks
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'infrastructure'
                downloadPath: '$(System.ArtifactsDirectory)'
            - task: UsePythonVersion@0
              displayName: Configuring Python Version
              inputs:
                versionSpec: '3.x'
                addToPath: true
                architecture: 'x64'
            # - task: configuredatabricks@0
            #   displayName: Configuring Databricks $(ArmOutputs.databricksWorkspaceName)
            #   inputs:
            #     url: '$(DatabricksWorkspaceURL)'
            #     token: '$(DatabricksPAT)'
            # - task: databricksDeployScripts@0
            #   inputs:
            #     authMethod: 'bearer'
            #     bearerToken: '$(DatabricksPAT)'
            #     region: 'westeurope'
            #     localPath: '$(System.ArtifactsDirectory)/${{ parameters.artifactName }}/${{ parameters.deploymentConfig.name }}/'
            #     databricksPath: '${{ parameters.deploymentConfig.workspaceFolder }}'