jobs:
  - deployment: 
    displayName: Azure Databricks Deployment
    environment: develop
    dependsOn: databricksbuild
    strategy:
      runOnce:
        deploy:
          steps:
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'databricks'
                downloadPath: '$(System.ArtifactsDirectory)'

            - powershell: |
                cd $(System.ArtifactsDirectory)
                Get-ChildItem -Recurse

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: 'MVP Sponsorship'
                subscriptionId: '337ba254-3aa0-4551-ba8e-89debefaa373'
                action: 'Create Or Update Resource Group'
                resourceGroupName: 'RG-ARMdatapipeline'
                location: 'North Europe'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.ArtifactsDirectory)\databricks\infrastructure\databricks.json'
                deploymentMode: 'Incremental'

            - task: databricksClusterTask@0
              inputs:
                authMethod: 'servicePrincipal'
                applicationId: 'e831ed10-140d-419f-a4aa-4c48965372d7'
                spSecret: '$(SPNSecret)'
                resourceGroup: 'RG-ARMdatapipeline'
                workspace: 'databricks5zpayvr2rt6ki'
                subscriptionId: '337ba254-3aa0-4551-ba8e-89debefaa373'
                tenantId: '47832e2c-ecb7-4a68-b534-b142a21317f0'
                region: 'westeurope'
                sourcePath: 'fds'