parameters:
  - name: resourceConfiguration
    type: object

jobs:
  - deployment: 
    displayName: Azure Databricks Deployment
    environment: develop
    dependsOn: databricksbuild
    strategy:
      runOnce:
        deploy:
          steps:
            
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'databricks'
                downloadPath: '$(System.ArtifactsDirectory)'

            - task: AzureResourceManagerTemplateDeployment@3
              inputs:
                deploymentScope: 'Resource Group'
                azureResourceManagerConnection: $(serviceConnection)
                subscriptionId: $(subscriptionId)
                action: 'Create Or Update Resource Group'
                resourceGroupName: ${{ parameters.resourceConfiguration.databricksWorkspaceResourceGroup }}
                location: 'North Europe'
                templateLocation: 'Linked artifact'
                csmFile: '$(System.ArtifactsDirectory)\databricks\infrastructure\databricks.json'
                deploymentMode: 'Incremental'
                deploymentOutputs: 'ArmOutputs'
            
            - powershell: |
                Write-Host "output $($ArmOutputs.databricksWorkspaceName)"
                Write-Host "output $($ArmOutputs)"
                Write-Host "output $(ArmOutputs.databricksWorkspaceName)"
                Write-Host "output $(ArmOutputs)"
                

            - ${{ each cluster in parameters.resourceConfiguration.infrastructure.clusters }}:
                - task: AzureCLI@2
                  displayName: Create Cluster
                  inputs:
                    azureSubscription: $(ServiceConnectionName)
                    scriptLocation: "scriptPath"
                    scriptType: "pscore"
                    scriptPath: '$(System.ArtifactsDirectory)\databricks\infrastructure\New-DatabricksCluster.ps1'
                    arguments: >
                      -clusterName ${{ cluster.name }}
                      -clusterConfigurationFile ${{ cluster.clusterConfigurationFile }}
                      -tenant $(tenant)
                      -spnClientId $(spnClientId)
                      -spnClientSecret $(spnClientSecret)
                      -databricksWorkspaceName $(ArmOutputs.databricksWorkspaceName)
                      -databricksWorkspaceResourceGroup ${{ parameters.resourceConfiguration.databricksWorkspaceResourceGroup }}