parameters:
- name: serviceConnection
  type: string
- name: resource
  type: object

jobs:
  - deployment: 
    displayName: Azure Web App Deployment
    environment: develop
    strategy:
      runOnce:
        deploy:
          steps:
            - task: DownloadBuildArtifacts@0
              inputs:
                buildType: 'current'
                downloadType: 'single'
                artifactName: 'drop'
                downloadPath: '$(System.ArtifactsDirectory)'
            
            - task: AzureRmWebAppDeployment@4
              inputs:
                ConnectionType: 'AzureRM'
                azureSubscription: ${{ parameters.serviceConnection }} # 'ServiceConnection'
                appType: 'webApp'
                WebAppName: ${{ parameters.resource.deployment.azureWebApp.name }} #'wa-udp-dotnetcore'
                packageForLinux: '$(System.ArtifactsDirectory)/**/*.zip'